server:
  port: 8080
  context-path: /imoocdemo
wechat:
    url:
    token: wx7b1e67aae4f216dc
    encodingaeskey:
    appid: wx7b1e67aae4f216dc
    appsecret: d8bc405c396addebe633c18ad55907be
    accessToken:
      server:
        class: com.qinchy.abc
    ticket:
      jsapi:
        server:
          class: com.qinchy.def
